export enum FilterOperationsEnum {
    EQ = 'EQ',
    N_EQ = 'N_EQ',
    GT = 'GT',
    GTE = 'GTE',
    LT = 'LT',
    LTE = 'LTE',
    IN = 'IN',
    NOT_IN = 'NOT_IN',
    LIKE = 'LIKE',
    I_LIKE = 'I_LIKE',
    NOT_LIKE = 'NOT_LIKE',
    NOT_I_LIKE = 'NOT_I_LIKE',
    BETWEEN = 'BETWEEN',
    NOT_BETWEEN = 'NOT_BETWEEN',
}